name: llms
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests
  - pip:
      - chardet
      - gradio==5.49.1
      - langchain_openai
      - langchain_core
      - langchain_chroma
      - langchain_community
      - langchain_text_splitters
      - langchain
      - pydantic
